name: Django Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: yourdbname
          POSTGRES_USER: yourdbuser
          POSTGRES_PASSWORD: yourdbpassword
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test
      env:
        DATABASE_URL: postgres://yourdbuser:yourdbpassword@localhost:5432/yourdbname
